# Writes each product's generated resource folders into monkey.jungle and
# beta.jungle, between their markers. Connect IQ finds resources-<qualifier>
# folders only next to the base resource folder, so every product names its
# own: resources/gen/round-WxH (art per screen size) and resources/gen/<product>
# (its launcher icon), whichever exist. Run by scripts/icons.sh. This file is
# the same in GarminOBD, GarminOsmoNano and GarminTPMS.
import os
import sys

sys.path.insert(0, os.path.dirname(__file__))
import devices  # noqa: E402

BEGIN = "# BEGIN generated by scripts/jungles.py: do not edit"
END = "# END generated"

lines = [BEGIN]
for d in devices.shipping():
    paths = [f"resources/gen/round-{d.width}x{d.width}", f"resources/gen/{d.id}"]
    paths = [p for p in paths if os.path.isdir(p)]
    if paths:
        lines.append(f"{d.id}.resourcePath = $({d.id}.resourcePath);{';'.join(paths)}")
lines.append(END)
block = "\n".join(lines) + "\n"

for jungle in ("monkey.jungle", "beta.jungle"):
    text = open(jungle).read()
    if BEGIN in text:
        head, rest = text.split(BEGIN, 1)
        text = head + block + rest.split(END, 1)[1].lstrip("\n")
    else:
        text = text.rstrip("\n") + "\n\n" + block
    open(jungle, "w").write(text)
    print(f"ok  {jungle} ({len(lines) - 2} products)")
