# Writes the generated resource paths into monkey.jungle and beta.jungle, between
# their markers: Connect IQ finds resources-<qualifier> folders only next to
# resources/, so each product names its own gen/ folders. Run by scripts/icons.sh.
import os
import subprocess

BEGIN = "# BEGIN generated by scripts/jungles.py: do not edit"
END = "# END generated"

lines = [BEGIN]
for row in subprocess.check_output(["python3", "scripts/devices.py", "--list"], text=True).split("\n"):
    if not row.strip():
        continue
    product, width = row.split()[:2]
    paths = [f"gen/resources-round-{width}x{width}", f"gen/resources-{product}"]
    paths = [p for p in paths if os.path.isdir(p)]
    if paths:
        lines.append(f"{product}.resourcePath = $({product}.resourcePath);{';'.join(paths)}")
lines.append(END)
block = "\n".join(lines) + "\n"

for jungle in ("monkey.jungle", "beta.jungle"):
    text = open(jungle).read()
    if BEGIN in text:
        head, rest = text.split(BEGIN, 1)
        text = head + block + rest.split(END, 1)[1].lstrip("\n")
    else:
        text = text.rstrip("\n") + "\n\n" + block
    open(jungle, "w").write(text)
    print(f"ok  {jungle} ({len(lines) - 2} products)")
